# Generated by Django 5.2 on 2025-05-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="description",
            new_name="task",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="title",
        ),
    ]
